version: "3"

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./src/test/resources/rabbitmq/rabbitmq-broker.json:/opt/definitions.json:ro
      - ./src/test/resources/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  app-container:
    image: npiper/aec-parties-scraper
    ports:
      - 8085:8080
    environment:
      - messaging.hostname=rabbitmq-container
    depends_on:
      - rabbitmq-container